using OPUSERP.Data.Entity;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OPUSERP.CLUB.Data.Notice
{
    [Table("NoticeInfo", Schema = "Club")]
    public class NoticeInfo : Base
    {
        public string subject { get; set; }

        [Column(TypeName = "text")]
        public string notice { get; set; }

        public string url { get; set; } //Notice Attatchments If any

        public string noticeType { get; set; } //From Master Data NoticeType

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? date { get; set; }

        public string slNo { get; set; } //AutoGenerated, 

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? validiTyTill { get; set; } // Show Till

        public int status { get; set; } //1 = publish , 0 = Unpublish
    }
}
