using System;

namespace OPUSERP.Areas.HRPMSACR.Models
{
    public class EmployeesInfoViewModel
    {        
        public int? EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpNameBn { get; set; }
        public string OfficEmailID { get; set; }
        public string Status { get; set; }
        public string MaritalStatus { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string PerDistrict { get; set; }
        public string PreDistrict { get; set; }
        public string OfficMobile { get; set; }
        public string Mobile { get; set; }
        public string BirthDate { get; set; }
        public string JoiningDate { get; set; }
        public string PrlDate { get; set; }
        public string SSNo { get; set; }
        public string FileNo { get; set; }
        public string PFAC { get; set; }
        public string ImagePath { get; set; }
        public string NationalID { get; set; }
        public string DesignationName { get; set; }
        public string JoiningDesignationName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DivisionName { get; set; }
        public string SalaryScale { get; set; }
        public decimal? BasicAmount { get; set; }
        public int? NoOfChild { get; set; }
        public string JoinDatePresentPosition { get; set; }
        public string JobUnderSupervisor { get; set; }
        public string EducationalQual { get; set; }
        public string LastEducation { get; set; }
        public string JobDuration { get; set; }
        public string JobDurationAsBranchManger { get; set; }
        public string JobDurationAsZonalHead { get; set; }
        public string JobDurationAsOthers { get; set; }
        public string DiplomaName { get; set; }
        public string DiplomaYearOne { get; set; }
        public string DiplomaYearTwo { get; set; }
        //public string YearOne { get; set; }
        //public string YearTwo { get; set; }
        public string ProfQName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string RewardsList { get; set; }
        public string PunishmentLetterNo { get; set; }
        public string PunishmentDate { get; set; }
        public string PunishmentList { get; set; }
        public string LastPromotionDate { get; set; }
        public string fromDate { get; set; }
        public string toDate { get; set; }
        public int? AssesmentId { get; set; }
        public string assessmentNo { get; set; }
        public string assessmentYear { get; set; }
        public string AssessmentDate { get; set; }
        public string BankName { get; set; }
        public string durationInRecommendetor { get; set; }
        public string goalAchievement { get; set; }
        public string SignatoryPath { get; set; }
        public string FinalSignatoryPath { get; set; }
        public string RecommendetorPath { get; set; }
        public string OwnSignaturePath { get; set; }
        public string HRUserSignaturePath { get; set; }
        public string OwnSignaturePathForm { get; set; }
        public string specialComment { get; set; }
        public string moralComment { get; set; }
        public string moralCommentSignatory { get; set; }
        public string intellectualComment { get; set; }
        public string intellectualCommentSignatory { get; set; }
        public int? promotionalQualification { get; set; }
        public int? promotionalQualificationSignatory { get; set; }
        public string subjectiveComment { get; set; }
        public string subjectiveCommentSignatory { get; set; }
        public string trainingComment { get; set; }
        public string otherRecommendation { get; set; }
        public string remarks { get; set; }
        public string signatoryRemarks { get; set; }
        public string specificJob { get; set; }
        public int? livingStandard { get; set; }
        public int? evaluationType { get; set; }
        public string disAgreementComment { get; set; }
        public string additionalComment { get; set; }
        public Int64 Totalmarks { get; set; }
        public string InWordMarks { get; set; }
        public string RecommendatorDesignation { get; set; }
        public string RecommendatorEmpCode { get; set; }
        public string RecommendatorName { get; set; }        
        public string SignatoryEmpCode { get; set; }
        public string SignatoryDesignation { get; set; }
        public string SignatoryName { get; set; }
        public string recommendationDate { get; set; }
        public string signatoryDate { get; set; }       
        public int? statusInfoId { get; set; }
        public string evaluationComments { get; set; }
        public int? evaluationCommentsHeadId { get; set; }
        public string commentsName { get; set; }
        public decimal? commentsMark { get; set; }
        public string recomWorkStation { get; set; }
        public string YearOne { get; set; }
        public string YearTwo { get; set; }
        public string languageUsage { get; set; }
        public string signlanguageUsage { get; set; }
        public string acrType { get; set; }

        //Assessment Sixth Part
        public DateTime? receivingDate { get; set; }
        public DateTime? hrUserDate { get; set; }
        public string responsibleUser { get; set; }
        public string hrUserName { get; set; }
        public string hrUserDesignation { get; set; }
        public string hrEmpCode { get; set; }
        public string reasonOfLate { get; set; }
        public string actionOnApplication { get; set; }
    }
    public class EmployeesAcrDGMtoAboveViewModel
    {        
        public int? EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpNameBn { get; set; }
        public string OfficEmailID { get; set; }
        public string Status { get; set; }
        public string MaritalStatus { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string PerDistrict { get; set; }
        public string PreDistrict { get; set; }
        public string OfficMobile { get; set; }
        public string Mobile { get; set; }
        public string BirthDate { get; set; }
        public string JoiningDate { get; set; }
        public string PrlDate { get; set; }
        public string SSNo { get; set; }
        public string FileNo { get; set; }
        public string PFAC { get; set; }
        public string ImagePath { get; set; }
        public string NationalID { get; set; }
        public string DesignationName { get; set; }
        public string JoiningDesignationName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DivisionName { get; set; }
        public string SalaryScale { get; set; }
        public decimal? BasicAmount { get; set; }
        public int? NoOfChild { get; set; }
        public string JoinDatePresentPosition { get; set; }
        public string JobUnderSupervisor { get; set; }
        public string EducationalQual { get; set; }
        public string LastEducation { get; set; }
        public string JobDuration { get; set; }
        public string JobDurationAsBranchManger { get; set; }
        public string JobDurationAsZonalHead { get; set; }
        public string JobDurationAsOthers { get; set; }
        public string DiplomaName { get; set; }
        public string DiplomaYearOne { get; set; }
        public string DiplomaYearTwo { get; set; }
        //public string YearOne { get; set; }
        //public string YearTwo { get; set; }
        public string ProfQName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string RewardsList { get; set; }
        public string PunishmentLetterNo { get; set; }
        public string PunishmentDate { get; set; }
        public string PunishmentList { get; set; }
        public string LastPromotionDate { get; set; }
        public string fromDate { get; set; }
        public string toDate { get; set; }
        public int? AssesmentId { get; set; }
        public string assessmentNo { get; set; }
        public string assessmentYear { get; set; }
        public string AssessmentDate { get; set; }
        public string BankName { get; set; }
        public string durationInRecommendetor { get; set; }
        public string goalAchievement { get; set; }
        public string SignatoryPath { get; set; }
        public string FinalSignatoryPath { get; set; }
        public string RecommendetorPath { get; set; }
        public string OwnSignaturePath { get; set; }
        public string HRUserSignaturePath { get; set; }
        public string OwnSignaturePathForm { get; set; }
        public string specialComment { get; set; }
        public string moralComment { get; set; }
        public string moralCommentSignatory { get; set; }
        public string intellectualComment { get; set; }
        public string intellectualCommentSignatory { get; set; }
        public int? promotionalQualification { get; set; }
        public int? promotionalQualificationSignatory { get; set; }
        public string subjectiveComment { get; set; }
        public string subjectiveCommentSignatory { get; set; }
        public string trainingComment { get; set; }
        public string otherRecommendation { get; set; }
        public string remarks { get; set; }
        public string signatoryRemarks { get; set; }
        public string specificJob { get; set; }
        public int? livingStandard { get; set; }
        public int? evaluationType { get; set; }
        public string disAgreementComment { get; set; }
        public string additionalComment { get; set; }
        public Int64 Totalmarks { get; set; }
        public string InWordMarks { get; set; }
        public string RecommendatorDesignation { get; set; }
        public string RecommendatorEmpCode { get; set; }
        public string RecommendatorName { get; set; }        
        public string SignatoryEmpCode { get; set; }
        public string SignatoryDesignation { get; set; }
        public string SignatoryName { get; set; }
        //Fsignatory
        public string fSignatoryCode { get; set; }
        public string fSignatoryDesignation { get; set; }
        public string fSignatoryName { get; set; }

        public string recommendationDate { get; set; }
        public string signatoryDate { get; set; }       
        public int? statusInfoId { get; set; }
        public string evaluationComments { get; set; }
        public int? evaluationCommentsHeadId { get; set; }
        public string commentsName { get; set; }
        public decimal? commentsMark { get; set; }
        public string recomWorkStation { get; set; }
        public string YearOne { get; set; }
        public string YearTwo { get; set; }
        public string languageUsage { get; set; }
        public string signlanguageUsage { get; set; }
        public string acrType { get; set; }

        //Assessment Sixth Part
        public DateTime? receivingDate { get; set; }
        public DateTime? hrUserDate { get; set; }
        public string responsibleUser { get; set; }
        public string hrUserName { get; set; }
        public string hrUserDesignation { get; set; }
        public string hrEmpCode { get; set; }
        public string reasonOfLate { get; set; }
        public string actionOnApplication { get; set; }
    }
}
