using OPUSERP.SCM.Data.Entity.MasterData;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OPUSERP.SCM.Services.MasterData.Interfaces
{
    public interface IAutoGeneratedNumberService
    {
        Task<int> SaveAutoGeneratedNumber(AutoGeneratedNumber autoGeneratedNumber);
        Task<IEnumerable<AutoGeneratedNumber>> GetAutoGeneratedNumberList();
        
        Task<AutoGeneratedNumber> GetAutoGeneratedNumberById(int id);
        Task<bool> DeleteAutoGeneratedNumberById(int id);
    }
}
