namespace OPUSERP.Areas.SCMMasterData.Models.Lang
{
    public class AutoGeneratedNumberLn
    {
        public string title { get; set; }
        public string autogenCategory { get; set; }
        public string isEmpCode { get; set; }
        public string digit { get; set; }
        public string isDate { get; set; }
        public string alphaNumeric { get; set; }
        public string numericStartPoint { get; set; }
        public string speratedSign { get; set; }
        public string format { get; set; }
       
        public string action { get; set; }
    }
}
