using Microsoft.EntityFrameworkCore;
using OPUSERP.Data;
using OPUSERP.SCM.Data;
using OPUSERP.SCM.Data.Entity.MasterData;
using OPUSERP.SCM.Services.MasterData.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Dostavi.Services.MasterData
{
    public class AutoGeneratedNumberService : IAutoGeneratedNumberService
    {
        private readonly ERPDbContext _context;

        public AutoGeneratedNumberService(ERPDbContext context)
        {
            _context = context;
        }
        public async Task<int> SaveAutoGeneratedNumber(AutoGeneratedNumber autoGeneratedNumber)
        {
            if (autoGeneratedNumber.Id != 0)
            {
                autoGeneratedNumber.updatedBy = autoGeneratedNumber.createdBy;
                autoGeneratedNumber.updatedAt = DateTime.Now;
                _context.AutoGeneratedNumbers.Update(autoGeneratedNumber);
            }
            else
            {
                autoGeneratedNumber.createdAt = DateTime.Now;
                _context.AutoGeneratedNumbers.Add(autoGeneratedNumber);
            }

            await _context.SaveChangesAsync();
            return autoGeneratedNumber.Id;
        }

        public async Task<IEnumerable<AutoGeneratedNumber>> GetAutoGeneratedNumberList()
        {
            return await _context.AutoGeneratedNumbers.AsNoTracking().ToListAsync();
        }

      

        public async Task<AutoGeneratedNumber> GetAutoGeneratedNumberById(int id)
        {
            return await _context.AutoGeneratedNumbers.FindAsync(id);
        }

        public async Task<bool> DeleteAutoGeneratedNumberById(int id)
        {
            _context.AutoGeneratedNumbers.Remove(_context.AutoGeneratedNumbers.Find(id));
            return 1 == await _context.SaveChangesAsync();
        }
    }
}
